### ISSUE TITLE
NoClassDefFoundError med versjon 5.0.9

### ISSUE THREAD

**Issue by mrsladek** [navikt/boot-cluster-conditionals#58]
Ved oppstart av appen med versjon 5.0.9 får man:
```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/enums/EnumEntriesKt
	at no.nav.boot.conditionals.Cluster.<clinit>(Cluster.kt:16)
	at no.nav.foreldrepenger.ws.proxy.FpWsProxyApplication.main(FpWsProxyApplication.java:19)
Caused by: java.lang.ClassNotFoundException: kotlin.enums.EnumEntriesKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 2 more
```

noen ekstra deps vi mangler? Virker helt ok med 5.0.8.

**Comment by jan-olaveide** [comment]
https://youtrack.jetbrains.com/issue/KT-58021.  Skal sjekke om dette kan løses i biblioteket og ikke i de enkelte repos
